use_frameworks!

platform :ios, '8.0'

target 'BGLDNetworking-kit_Example' do
  pod 'BGLDNetworking-kit', :path => '../'

  target 'BGLDNetworking-kit_Tests' do
    inherit! :search_paths

    
  end
end
